development:
  adapter: mysql
  database: jasonrush_development
  username: root
  password: 

test:
  adapter: mysql
  database: jasonrush_test
  username: root
  password: 

production:
  adapter: mysql
  database: jasonrush_production
  username: root
  password: 

